codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error
    
    patch:
      default:
        target: 80%
        threshold: 10%
        if_ci_failed: error

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/*.test.ts"
  - "**/*.d.ts"
  - "dist/**"
  - "coverage/**"
  - "node_modules/**"
  - "src/abis/**"
  - "**/types.ts"
  - "**/index.ts"
  - "src/main.ts"
  - "src/test-helpers/*.ts"


