services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=cr.qa
      - DATABASE_CONNECTION_STRING=postgresql://test:test@postgres:5432/test
      - THE_GRAPH_API_KEY=106677  
    depends_on:
      postgres:
        condition: service_healthy
